#!/usr/bin/env bash
# Install nginx on your web-01
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo ufw allow "Nginx HTTP"
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
