#!/usr/bin/env bash
# bash script to install and setup haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 56172-web-01 54.174.107.234:80 check
   server 56172-web-02 100.26.229.61:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
