#!/usr/bin/env bash
# script that generates a MySQL dump and creates a compressed archive out of it.
sudo mysqldump --password="$1" --user=root --all-databases > backup.sql
tar -cvzf "$(date +"%d-%m-%Y").tar.gz" backup.sql
