#!/usr/bin/env bash
# a Bash script that displays:To infinity and beyond indefinitely
#With a sleep 2 in between each iteration I am invincible!!! when receiving a SIGTERM signal
#!/bin/bash

# Trap SIGTERM signal
trap "echo I am invincible!!!" SIGTERM

# Infinite loop
while true; do
  # Display the message
  echo "To infinity and beyond"

  # Sleep for 2 seconds
  sleep 2
done
