#!/usr/bin/env bash
#script dsiplaying "Best School 10 times, but for the 9th iteration, displays "Best School" and "Hi" on a new line.

name=0
while [ $name -lt 10 ]

do
	echo "Best School"
	if [ $name -eq 9 ]
	then
		echo "Hi"
	fi
	name=$((name+1))
done
