#!/usr/bin/env bash
#script dsiplaying "Best School 10 times, but for the 9th iteration, displays "Best School" and "Hi" on a new line.

name=0
while [ $name -lt 10 ]
do
	if [ $name -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	(( name ++ ))
done
