#!/usr/bin/env bash
#script displaying 8 in the Chinese culture4 in the Chinese culture

i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck!"
	elif [ $i -eq 8 ]
	then
		echo "good luck!"
	else
		echo "Best School!"
	fi
	((i++))
done
