#!/usr/bin/env bash
#fixes server to listen on port 8080
sudo chmod 777 /etc/nginx/nginx.conf
sudo pkill apache2
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
